### ISSUE TITLE
Предложение добавить функционал

### ISSUE THREAD

**Issue by RustamKhamitov** [RussianFox/imap#1]
1. Добавить метки в которых бы отображались координаты.
2. Поиск по координатам в поле поиска google и добавление метки если таковая находится.
3. Исправить поиск в Хостах не по карте, а в самом списке узлов в поле Хосты.
4. Поиск по хосту в списке линкуемых объектов, и выбор несколько хостов при линке к одному хосту.

**Comment by RussianFox** [comment]
По 3 и 4 пункту не понял.
Что не работает?

**Comment by RustamKhamitov** [comment]
3. Когда ввожу имя устройства в поиске "Hosts" на карте отображается то имя устройства которое я ввел, при этом в списке ниже выделение введенного хоста не происходит, хотя раньше все работало.
4. На самом хосте при на жатии на "Add link" появляется список хостов в котором можно выбрать линкуемый хост, так вот поиск конкретного имени узла не работает, и сделать линки с одного устройства сразу на несколько тоже не работает.

**Comment by RussianFox** [comment]
Линки с одного на несколько хостов должны работать. Ошибка была, но я исправил ее давно довольно.
Поиск должен работать тоже. Но вот как раз он зависит от браузера. Попробуйте на другом.

**Comment by RustamKhamitov** [comment]
По нескольким линкам все работает, но поиск отказывается пробовал тремя браузерами хром, лисой, ie результат один поиск не работает, ни при поиске линков ни при поиске хостов в списке на карте.

**Comment by RussianFox** [comment]
Хорошо, а вы умеете отладчиком js пользоваться?
Вкратце:
когда вы вводите любой символ в поле поиска хостов на карте, запускается функция getHostsFilter1T, через секунду она запускает getHostsFilter1, которая запускает ДЛЯ КАЖДОГО хоста функцию hostsFilter

Проверьте, что из этого у вас происходит, а что нет.

**Comment by RustamKhamitov** [comment]
Хм странно, сегодня обновился до последней версии поиск в линках заработал, а вот поиск в узлах так и не работает.

**Comment by RussianFox** [comment]
Тогда я, кажется, знаю, в чем причина. Напишу, когда поправлю.

**Comment by RussianFox** [comment]
Что с поиском в списке хостов в последней бета-версии?

**Comment by RustamKhamitov** [comment]
Без изменений, хосты на карте показываются а в списке выделение запрашиваемого хоста не происходит. Пробовал разными версиями браузеров.

**Comment by RussianFox** [comment]
А нельзи ли как-то сделать учетку гостевую и дать доступ мне, чтобы я проверил? Потому что это последний глюк, который мешает релизу, а я никак не могу его выловить. Чтобы не светить, пришлите мне на почту lisss81@yandex.ru

Предлагаю сделать несколько фейковых тестовых узлов, чтобы на них этот глюк распространялся, дать этой учетке права чтения только на них, открыть доступ по нестандартному порту, чтобы сохранить конфиденциальность.
