### ISSUE TITLE
вопросы и замечания

### ISSUE THREAD

**Issue by Evgeniy12345** [RussianFox/imap#15]
2.2.7
1) Иногда окно вылезает за пределы
2) "Контроль карты" привязан к интервалу обновления страницы? Т.к. приходится выставлять значение 15-30 сек, то приходится его отключать/включать постоянно, чтобы хоть что-то успеть посмотреть... :) Не помешала бы опция в настройках.
3) "Только с триггерами", показываются все узлы сети с триггерами, хотя вроде логичнее показывать только узлы сети со сработавшими триггерами, чтобы при включенном контроле карты сразу происходило позиционирование карты на эти узлы сети.
4) Пропало стандартное контекстное меню со скриптами (ping, tracert)
5) Функционала уже на любой вкус, но т.к. имею дело со спутниковыми приемниками, не помешала бы погода, что-то похожее сделано у бразильцев https://github.com/aristotelesaraujo/zabbix-geolocation.
6) Возникла идея, часть опрашиваемых параметров (например ping time (интервал опроса 15 сек), всего около 10 на каждом узле сети) штатными средствами заббикса заносить в инвентарные данные, чтобы видеть их в контекстном меню на интерактивной карте. Как думаете, сильно скажется на производительности?
7) Контекстное меню в последней версии для 2.2 - это Google streetview?
8) При включении Яндекс Траффик
![imap2](https://cloud.githubusercontent.com/assets/12445099/7632670/fd9c4466-fa57-11e4-978a-654a60ab9cf3.jpg)

**Comment by RussianFox** [comment]
1. В процессе придумывания обхода.
2. Контроль карты - это спозиционировать карту так, чтобы туда попали все
узлы. Соответсвенно, позиционирование происходит после обновления страницы,
а потом при каждом обновлении списка хостов в зависимости от галочки.
Состояние галочки сохраняется штатными средствами Zabbix
3. Выберите нужную важность и все будет.
4. Оно должно быть при клике по названию хоста. Если нет - уточните.
5. Скриншот бы.
6. Если я правильно понял, то вы своим способом будете изменять инвентарные
данные. Если так, то на производительности imap никак не скажется.
7. Google Street View и Tools у хоста.
8. Это косяк самого плагина Яндекса. Если честно - просто лень разбираться.
Не самый нужный функционал, по-моему.

14 мая 2015 г., 16:41 пользователь Evgeniy12345 <notifications@github.com>
написал:

**Comment by Evgeniy12345** [comment]
1) Понятно, не так часто бывает, можно привыкнуть
2) Непонятно, правильно ли поняли, опишу ситуацию. Увеличиваю масштаб и иногда сразу же меня выкидывает на общий вид, т.е. приходится снимать галочку, фокусироваться на объект, смотреть что нужно, потом опять ставить галочку, чтобы вернуться на общий вид. Увеличить интервал в настройках профиля неприемлимо.
3) Точно
4) Точно, думал при правом клике.
5) Значек (Облачно, дождь) и значение температуры рядом с узлом сети. Пробовал ставить когда-то на виртуаку, сейчас надо все по-новой делать, чтобы заскринить.
6) Ясно, спасибо.
7) Tools не вижу, может смотрю не туда.
8) Тоже не нужен.

**Comment by RussianFox** [comment]
2. Ну в принципе, все верно. Все так и задумывалось. Я думаю, вам просто
нужна кнопка возврата к общему плану. Приделаю.
5. Интересно было-бы узнать источник данных. Посмотрите проект
OpenWeatherMap, можно прикрутить данные оттуда.
7. Под названием хоста есть еще кнопочка Tools (Инструменты). Если у вас
нет, рекомендую обновиться.
14.05.2015 17:22 пользователь "Evgeniy12345" <notifications@github.com>
написал:

**Comment by Evgeniy12345** [comment]
2) Не обязательно, галочка работает как кнопка, привыкнем.
5) Вполне подойдет, либо можно прикрутить погодный слой на картах гугл.
7) Может опять не там ищу)
![imap2](https://cloud.githubusercontent.com/assets/12445099/7647318/4c7b0c10-fadb-11e4-9658-19783ab205f1.jpg)

**Comment by RussianFox** [comment]
![image](https://cloud.githubusercontent.com/assets/11329995/7647454/9a51b4dc-fadd-11e4-8798-36bbf5d21245.png)

**Comment by Evgeniy12345** [comment]
На виртуалке обновился из ветки develop, тоже самое - нет меню.

**Comment by Evgeniy12345** [comment]
Ошибок на странице нет. Firebug говорит все отлично. Что я еще могу у себя сделать, чтобы как-то помочь разобраться почему его нет?

**Comment by RussianFox** [comment]
Прикрутил запрос погоды для точки через контекстное меню. Попробуйте из ветки Develop

**Comment by RussianFox** [comment]
Вот вроде бы и все вопросы решились.

**Comment by Evgeniy12345** [comment]
Лучше не придумать, завтра опробую на основном сервере.
Единственное, в пятницу поставил 1.1.6 на виртуалке, оставил открытой карту. Сейчас глянул, сработавших триггеров совсем нет, всё зеленое. Ставил под конец дня и не обратил внимания так стало после обновления или же спустя какое-то время. Обновил страницу, попробовал в другом браузере - без изменений. Накатил версию из develop, все равно вся карта зеленая и окно триггеров пустое. Оставил в таком состоянии до завтра.

**Comment by volerster** [comment]
Добрый день.

Подскажите планируется добавление просто точек на карту, для обозначения как проложен кабель?

**Comment by RussianFox** [comment]
Планируется. Кстати, если бы вы задали этот вопрос в отдельной теме, при появлении этого функционала я бы смог автоматически вас оповестить.

**Comment by Evgeniy12345** [comment]
На основной машине полет нормальный. Еще раз спасибо, что поделились и продолжаете улучшать! И отдельное спасибо за контекстное меню для 2.2.
