### ISSUE TITLE
Ссылка на комплексные экраны

### ISSUE THREAD

**Issue by Evgeniy12345** [RussianFox/imap#18]
Если узлу сети назначен комплексный экран в шаблоне, то в заббиксе попасть на него можно либо с карты, либо как-то через поиск.
На штатной карте меню выглядит так
![imap2](https://cloud.githubusercontent.com/assets/12445099/7725146/897c41d2-ff00-11e4-9f47-aa8caed21fd7.jpg)
В imap контекстное меню того же узла сети отличается:
![imap2](https://cloud.githubusercontent.com/assets/12445099/7725198/f8dc1cfa-ff00-11e4-87b5-be6ee3b4b542.jpg)
Просьба куда-нибудь прилепить ссылку на комплексный экран из назначенного шаблона.

**Comment by RussianFox** [comment]
Не нашел, как вы такое получили...
Просьба, щелкните по этой ссылке и с открывшегося окна скопируйте сюда ссылку. Можете вырезать все, что ДО знака вопроса.

**Comment by Evgeniy12345** [comment]
с карты: host_screen.php?sid=00945eca987ba3fb&hostid=10688
через поиск: host_screen.php?hostid=10688&sid=00945eca987ba3fb

**Comment by Evgeniy12345** [comment]
var screen = { label: mlocale ('Screens'), url: 'host_screen.php?'+getSID()+'hostid='+hh, clickCallback: function(){ popupFrame('host_screen.php?'+getSID()+'form_refresh=1&fullscreen=1&filterState=0&hostid='+hh); return false; } };

В Tools запихал, но не совсем то что надо получилось из-за размера комплексного экрана, окно для него совсем маловато...
