### ISSUE TITLE
графики

### ISSUE THREAD

**Issue by Evgeniy12345** [RussianFox/imap#19]
Очень удобно, что графики из меню Tools открываются в новом окне, но его бы немного расширить, чтобы все окна фильтра всегда были в одну строку и графики с размерами по умолчанию всегда влезали.
![imap2](https://cloud.githubusercontent.com/assets/12445099/7726503/4680fed0-ff0b-11e4-90df-51df41444b7d.jpg)

И при переключении между графиками в этом окне слетает полноэкранный режим.
![imap2](https://cloud.githubusercontent.com/assets/12445099/7726421/a14d3834-ff0a-11e4-94ff-1c9d3f9bbf5b.jpg)

**Comment by RussianFox** [comment]
Обновитесь из ветки version-1.1.6, пофиксил

**Comment by Evgeniy12345** [comment]
Полноэкранный режим больше не слетает, по поводу размеров окна увеличил для себя ширину до 1000
jQuery(container).dialog({maxWidth:'100%', maxHeight:'100%', width:1000, height:650, resizable:true})
