### ISSUE TITLE
Поддержка PostgreSQL

### ISSUE THREAD

**Issue by VadimRozhik** [RussianFox/imap#5]
Добрый день!

Настроил imap с использованием PostgreSQL, работает.
Есть желание добавить поддержку постгреса в релиз?

**Comment by RussianFox** [comment]
Уже добавлено.
А вот инструкции и аналога файла tables.sql для PostgreSQL не хватает. Сможете помочь?

**Comment by VadimRozhik** [comment]
Проверка наличия таблиц выдавала ошибку, поменял код SQL в imap.php, 395 строка:
$glinks = DBfetchArray(DBselect("select column_name, data_type, character_maximum_length from INFORMATION_SCHEMA.COLUMNS where table_name = 'hosts_links_settings'"));
if (count($glinks)==0) $check_links = false;
$glinks = DBfetchArray(DBselect("select column_name, data_type, character_maximum_length from INFORMATION_SCHEMA.COLUMNS where table_name = 'hosts_links'"));
if (count($glinks)==0) $check_links = false;

tables.sql:

CREATE TABLE hosts_links_settings (
    ids bigint NOT NULL,
    color character varying(30) DEFAULT NULL,
    weight integer,
    opacity integer,
    dash character varying(100) DEFAULT NULL
);
ALTER TABLE ONLY hosts_links_settings ADD CONSTRAINT hosts_links_settings_pkey PRIMARY KEY (ids);

CREATE SEQUENCE hosts_links_seq;
CREATE TABLE hosts_links (
    id bigint DEFAULT nextval('hosts_links_seq') NOT NULL,
    name character varying(300) DEFAULT NULL,
    host1 bigint NOT NULL,
    host2 bigint NOT NULL
);
ALTER TABLE ONLY hosts_links ADD CONSTRAINT hosts_links_pkey PRIMARY KEY (id);
ALTER TABLE ONLY hosts_links ADD CONSTRAINT hosts_unique UNIQUE (host1, host2);

Команда для добавления таблиц в БД из под рута:
sudo -u zabbix psql -U zabbix -W -d zabbix < table.sql
где
# sudo -u zabbix - действия от имени системного пользователя zabbix (иначе PosgreSQL не аутентифицирует пользователя),
-U zabbix - владелец БД,
-d zabbix - название БД.

To create table in PostgreSQL run under root:
# sudo -u zabbix psql -U zabbix -W -d zabbix < table.sql
where
sudo -u zabbix - act as system user 'zabbix' (otherwise PosgreSQL will not authenticate user),
-U zabbix - database owner,
-d zabbix - database name.

**Comment by RussianFox** [comment]
Отлично!

Только я проверку таблиц сделал другой, универсальной для всех баз. Проверяйте.

**Comment by VadimRozhik** [comment]
В master'е запрос для проверки:
Show tables from zabbix like 'hosts_links'

Мы об этой проверке говорим? В postgresql нет show tables, там \dt
zabbix=# Show tables from zabbix like 'hosts_links';
ERROR:  syntax error at or near "from"
LINE 1: Show tables from zabbix like 'hosts_links';
                    ^
SQL-запрос что я прислал работает и в mysql.

**Comment by RussianFox** [comment]
Не в master, в develop

Проверьте, если все ок, запулю в мастер.

**Comment by VadimRozhik** [comment]
imap.php из develop'а работает.
Спасибо!

**Comment by RussianFox** [comment]
Вам спасибо за файл схемы и инструкцию
